hreflang tags in head for SEO
straube/multiple-domain pull request #9
Opened 2017-11-20 16:16 UTC by cyberaleks

For SEO  purpose it should be helpful to have hreflang tags  in head for each domain.
- Fixed resolving host name to boolean. Code line 71.
- Added Reflang links to head for SEO purpose.
e.g.
```html
<link rel="alternate" hreflang="x-default" href="https://example.com/">
<link rel="alternate" hreflang="de-DE" href="https://de.example.com/">
```

2017-11-23 17:28 UTC, straube requested changes
Hi! Thanks for your contribution. I think we just need to address some minor cases. Could you tackle them?

2017-11-23 17:28 UTC, straube commented on multiple-domain/multiple-domain.php
> +            $fields .= $this->getDomainFields($i++, $domain, $values['base'], $values['lang']);
Hey @cyberaleks, it seems to me this part is not compatible with previous versions. Do you think we can handle this part to expect either a string (containing the optional base path) or an array (with the base path and lang code)?

Also, not everybody we'll use domains linked to different langs. I myself have a project that just uses a domain for part of the site due to some client requirements. I just wanted to make sure that lang is not required.

Thanks! :)

2017-11-25 10:30 UTC, cyberaleks commented
Hi, i made lang optional and backwards compatible.

2017-11-25 10:31 UTC, cyberaleks commented on multiple-domain/multiple-domain.php
> +            $fields .= $this->getDomainFields($i++, $domain, $values['base'], $values['lang']);
Fixed

2017-11-28 22:58 UTC, merged

2017-11-28 23:12 UTC, straube commented
Hey @cyberaleks! Thanks for adding those changes! The last updates are now public: https://wordpress.org/plugins/multiple-domain/ :)